# 許可された企業リスト（実装済み21社）
# このリストに含まれる企業のみが実行対象になります
allowed_companies:
  - 眞田鋼業株式会社
  - 有限会社金田商事
  - 木村金属（大阪）
  - 明鑫貿易株式会社
  - 東起産業（株）
  - 土金（大阪）
  - 大畑商事（千葉・大阪）
  - 千福商会（大阪）
  - 鴻祥貿易株式会社
  - 株式会社鳳山
  - 株式会社 春日商会　富山支店
  - 株式会社 春日商会　滋賀支店
  - 株式会社 春日商会　一宮本社
  - 安城貿易（愛知）
  - 東北キング
  - 株式会社八木
  - 有限会社　八尾アルミセンター
  - 株式会社 ヒラノヤ
  - 鴻陽産業株式会社 岐阜工場
  - 株式会社 大垣金属
  - 高橋商事株式会社


