services:
  - type: web
    name: price-scraper-app-std
    env: python
    plan: free
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app_std:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production



